version: '3.8'

services:
  backend:
    build: ./backend
    container_name: stremio-backend
    restart: unless-stopped
    ports:
      - "3001:3001"
    env_file:
      - ./backend/.env
    networks:
      - stremio-net

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Sao_Paulo
    volumes:
      - prowlarr-config:/config
    ports:
      - "9696:9696"
    networks:
      - stremio-net

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=info
      - LOG_HTML=false
      - CAPTCHA_SOLVER=none
      - TZ=America/Sao_Paulo
    ports:
      - "8191:8191"
    restart: unless-stopped
    networks:
      - stremio-net

volumes:
  prowlarr-config:

networks:
  stremio-net:
    driver: bridge
